version: "3.7"

x-php-defaults: &php-defaults
  build:
      args:
        user: developer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
  cap_add:
    - SYS_PTRACE
  security_opt:
    - apparmor:unconfined
  volumes:
    - ./build/php-ini-${PHP_INI_TEMPLATE}.ini:/usr/local/etc/php/conf.d/zz-force-conf.ini
    - ./build/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-www.conf
    - ./src:/var/www/html
  environment: &php-env-defaults
    PHP_INI_TEMPLATE: ${PHP_INI_TEMPLATE}
    MYSQL_HOST: ${DB_HOST}
    MYSQL_DATABASE: ${DB_DATABASE}
    MYSQL_USER: ${DB_USERNAME}
    MYSQL_PASSWORD: ${DB_PASSWORD}
  depends_on:
    - db

services:
  test:
    <<: *php-defaults
    environment:
      <<: *php-env-defaults
      FOREGROUND_PROCESS: php-fpm
      CONTAINER_ENABLED: 1
      SSHD_ENABLED: ${SSHD_ENABLED}
      PHP_INI_TEMPLATE: ${PHP_INI_TEMPLATE}
    ports:
      - "${HOST_SSHD_PORT}:22"
      - "9001:9001"
    restart: on-failure

  test-web:
    image: nginx:latest
    tty: true
    ports:
      - "${HOST_WEB_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - ./build/nginx-server-${ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./build/ssl:/etc/nginx/ssl
    depends_on:
      - "test"
    restart: on-failure

  db:
    image: mariadb:latest
    tty: true
    ports:
      - "${HOST_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: Fhnl;jrth_2ujdyj
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./runtime/mysql:/var/lib/mysql
      - ./build/my.cnf:/etc/mysql/my.cnf
    restart: on-failure
